version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: sismo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: sismo_db
      MYSQL_USER: sismouser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sismopassword}
    # Comentado para evitar conflictos con MySQL local
    # ports:
    #   - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbschema/:/docker-entrypoint-initdb.d/
    networks:
      - sismo-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Base de datos Neo4j
  neo4j:
    image: neo4j:4.4
    container_name: sismo-neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD:-password}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    ports:
      - "7474:7474"  # Puerto para interfaz HTTP
      - "7687:7687"  # Puerto para Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - sismo-network
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474", "-O", "/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Spring Boot
  backend:
    build:
      context: ./sismo-deteccion
      dockerfile: Dockerfile
    container_name: sismo-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      # Configuración de MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sismo_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-sismouser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-sismopassword}
      # Configuración de Neo4j local (en lugar de la instancia remota)
      SPRING_DATA_NEO4J_URI: bolt://neo4j:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: ${NEO4J_PASSWORD:-password}
      # Configuración JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8081:8080"
    networks:
      - sismo-network

  # Frontend React
  frontend:
    build:
      context: ./sismos-frontend
      dockerfile: Dockerfile
    container_name: sismo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - sismo-network

volumes:
  mysql_data:
  neo4j_data:
  neo4j_logs:

networks:
  sismo-network:
    driver: bridge